"""
modules/email_alerts.py
SMTP parent email alerts using Python smtplib (Gmail TLS port 587).
Sends HTML-formatted notifications for:
  - Low attendance (below subject threshold)
  - Consecutive absences
"""
import smtplib
import ssl
from email.mime.multipart import MIMEMultipart
from email.mime.text      import MIMEText
from datetime import datetime
from modules.db import get_db
import config


# ── Email log ─────────────────────────────────────────────────────────────────

def _log_email(usn: str, subject: str, recipient: str,
               status: str, error: str = "", alert_type: str = "absence"):
    """Log sent email to MongoDB email_logs collection."""
    db = get_db()
    db.email_logs.insert_one({
        "usn":        usn,
        "subject":    subject,
        "recipient":  recipient,
        "status":     status,
        "error":      error,
        "alert_type": alert_type,
        "sent_at":    datetime.utcnow(),
    })


# ── HTML builders ─────────────────────────────────────────────────────────────

def _build_absence_html(student_name: str, usn: str, subject: str,
                         absence_date: str, consecutive: int) -> str:
    return f"""<!DOCTYPE html>
<html>
<head><meta charset="UTF-8">
<style>
  body {{ font-family: Arial, sans-serif; background: #f4f6f9; margin: 0; padding: 0; }}
  .container {{ max-width: 600px; margin: 30px auto; background: #fff;
                border-radius: 10px; overflow: hidden;
                box-shadow: 0 4px 20px rgba(0,0,0,0.10); }}
  .header {{ background: linear-gradient(135deg, #1a237e, #283593);
             color: #fff; padding: 28px 32px; }}
  .header h1 {{ margin: 0; font-size: 22px; }}
  .header p  {{ margin: 4px 0 0; font-size: 13px; opacity: 0.85; }}
  .body  {{ padding: 28px 32px; color: #333; line-height: 1.7; }}
  .badge {{ display: inline-block; background: #e53935; color: #fff;
            border-radius: 6px; padding: 4px 12px; font-weight: bold;
            margin-bottom: 16px; font-size: 13px; }}
  table  {{ width: 100%; border-collapse: collapse; margin: 16px 0; }}
  td, th {{ padding: 10px 14px; border: 1px solid #e0e0e0; text-align: left; }}
  th     {{ background: #f0f4ff; color: #1a237e; font-weight: 600; }}
  .footer{{ background: #f0f4ff; text-align: center; padding: 16px;
            font-size: 12px; color: #666; }}
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>📋 SGBIT — Attendance Alert</h1>
    <p>Department of Computer Science &amp; Engineering, Belagavi</p>
  </div>
  <div class="body">
    <div class="badge">⚠️ Absence Notification</div>
    <p>Dear Parent / Guardian,</p>
    <p>This is to inform you that your ward <strong>{student_name}</strong>
       was marked <strong>ABSENT</strong> in the following session:</p>
    <table>
      <tr><th>Student Name</th><td>{student_name}</td></tr>
      <tr><th>USN</th>         <td>{usn}</td></tr>
      <tr><th>Subject</th>     <td>{subject}</td></tr>
      <tr><th>Date</th>        <td>{absence_date}</td></tr>
      <tr><th>Consecutive Absences</th>
          <td><strong style="color:#e53935">{consecutive}</strong></td></tr>
    </table>
    <p>Please ensure regular attendance. Students with attendance below
       <strong>the required threshold</strong> may not be permitted to appear
       in internal examinations as per SGBIT norms.</p>
    <p>For queries, contact the class teacher or department office.</p>
    <p>Regards,<br><strong>CSE Department, SGBIT Belagavi</strong></p>
  </div>
  <div class="footer">
    This is an automated alert generated by the SGBIT Attendance Management System.
  </div>
</div>
</body>
</html>"""


def _build_low_attendance_html(student_name: str, usn: str, subject: str,
                                current_pct: float, threshold: int) -> str:
    color = "#e53935" if current_pct < threshold - 10 else "#ff9800"
    return f"""<!DOCTYPE html>
<html>
<head><meta charset="UTF-8">
<style>
  body {{ font-family: Arial, sans-serif; background: #f4f6f9; margin: 0; padding: 0; }}
  .container {{ max-width: 600px; margin: 30px auto; background: #fff;
                border-radius: 10px; overflow: hidden;
                box-shadow: 0 4px 20px rgba(0,0,0,0.10); }}
  .header {{ background: linear-gradient(135deg, #b71c1c, #c62828);
             color: #fff; padding: 28px 32px; }}
  .header h1 {{ margin: 0; font-size: 22px; }}
  .header p  {{ margin: 4px 0 0; font-size: 13px; opacity: 0.85; }}
  .body  {{ padding: 28px 32px; color: #333; line-height: 1.7; }}
  .badge {{ display: inline-block; background: {color}; color: #fff;
            border-radius: 6px; padding: 4px 12px; font-weight: bold;
            margin-bottom: 16px; font-size: 13px; }}
  .pct-box {{ text-align: center; background: #fff3f3; border: 2px solid {color};
              border-radius: 12px; padding: 20px; margin: 20px 0; }}
  .pct-num {{ font-size: 3rem; font-weight: 700; color: {color}; }}
  table  {{ width: 100%; border-collapse: collapse; margin: 16px 0; }}
  td, th {{ padding: 10px 14px; border: 1px solid #e0e0e0; text-align: left; }}
  th     {{ background: #f0f4ff; color: #1a237e; font-weight: 600; }}
  .footer{{ background: #f0f4ff; text-align: center; padding: 16px;
            font-size: 12px; color: #666; }}
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>🚨 SGBIT — Low Attendance Warning</h1>
    <p>Department of Computer Science &amp; Engineering, Belagavi</p>
  </div>
  <div class="body">
    <div class="badge">⛔ Low Attendance Alert</div>
    <p>Dear Parent / Guardian,</p>
    <p>Your ward <strong>{student_name}</strong>'s attendance has dropped
       below the required minimum in the following subject:</p>
    <div class="pct-box">
      <div class="pct-num">{current_pct:.1f}%</div>
      <div>Current Attendance in <strong>{subject}</strong></div>
      <div style="font-size:0.85rem;color:#888;margin-top:4px">
        Required minimum: {threshold}%
      </div>
    </div>
    <table>
      <tr><th>Student Name</th>  <td>{student_name}</td></tr>
      <tr><th>USN</th>            <td>{usn}</td></tr>
      <tr><th>Subject</th>        <td>{subject}</td></tr>
      <tr><th>Current Attendance</th>
          <td><strong style="color:{color}">{current_pct:.1f}%</strong></td></tr>
      <tr><th>Required Minimum</th>
          <td><strong>{threshold}%</strong></td></tr>
    </table>
    <p>Immediate action is required. Students below the threshold will
       <strong>not be permitted</strong> to appear in internal examinations.</p>
    <p>Please contact the class teacher at the earliest.</p>
    <p>Regards,<br><strong>CSE Department, SGBIT Belagavi</strong></p>
  </div>
  <div class="footer">
    This is an automated alert generated by the SGBIT Attendance Management System.
  </div>
</div>
</body>
</html>"""


# ── Send helpers ──────────────────────────────────────────────────────────────

def _send_email(recipient: str, subject_line: str, html_body: str,
                usn: str, subject: str, alert_type: str) -> bool:
    if not config.EMAIL_SENDER or not config.EMAIL_PASSWORD:
        print("[email_alerts] SMTP credentials not configured — skipping.")
        return False
    if not recipient:
        return False

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject_line
    msg["From"]    = f"{config.EMAIL_SENDER_NAME} <{config.EMAIL_SENDER}>"
    msg["To"]      = recipient
    msg.attach(MIMEText(html_body, "html"))

    try:
        ctx = ssl.create_default_context()
        with smtplib.SMTP(config.SMTP_HOST, config.SMTP_PORT, timeout=10) as srv:
            srv.ehlo(); srv.starttls(context=ctx); srv.login(config.EMAIL_SENDER, config.EMAIL_PASSWORD)
            srv.sendmail(config.EMAIL_SENDER, recipient, msg.as_string())
        _log_email(usn, subject, recipient, "sent", alert_type=alert_type)
        return True
    except Exception as exc:
        _log_email(usn, subject, recipient, "failed", str(exc), alert_type=alert_type)
        print(f"[email_alerts] Failed to send email: {exc}")
        return False


# ── Public API ────────────────────────────────────────────────────────────────

def send_absence_alert(student: dict, subject: str,
                        absence_date: str, consecutive: int) -> bool:
    """Send an HTML absence alert email to the student's parent."""
    name  = student["name"]
    usn   = student["usn"]
    html  = _build_absence_html(name, usn, subject, absence_date, consecutive)
    return _send_email(
        recipient    = student.get("parent_email", ""),
        subject_line = f"[SGBIT] Attendance Alert — {name} absent in {subject}",
        html_body    = html,
        usn          = usn,
        subject      = subject,
        alert_type   = "absence",
    )


def send_low_attendance_alert(student: dict, subject: str,
                               current_pct: float, threshold: int) -> bool:
    """
    Send a LOW ATTENDANCE warning email when the student's attendance %
    drops below the subject threshold.
    """
    name  = student["name"]
    usn   = student["usn"]
    html  = _build_low_attendance_html(name, usn, subject, current_pct, threshold)
    return _send_email(
        recipient    = student.get("parent_email", ""),
        subject_line = f"[SGBIT] ⚠️ Low Attendance Warning — {name} in {subject} ({current_pct:.1f}%)",
        html_body    = html,
        usn          = usn,
        subject      = subject,
        alert_type   = "low_attendance",
    )


def get_email_logs(usn: str = None, limit: int = 50) -> list[dict]:
    """Fetch recent email send logs from MongoDB."""
    db    = get_db()
    query = {"usn": usn} if usn else {}
    logs  = list(db.email_logs.find(query, {"_id": 0}).sort("sent_at", -1).limit(limit))
    return logs
